import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-about',
  templateUrl: './contact.component.html',
 
})
export class ContactComponent implements OnInit {
  
  parentValue:any;
  test:any;

  constructor() { }

  ngOnInit() {
    this.parentValue = {
      "shipmentEvents": [
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "4ff5ffe0-2840-11e8-9a6e-7f663272511f",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8048,
              "longitude": -77.0925,
              "asOfTime": "2018-03-15T11:02:16.000Z",
              "receivedTime": "2018-03-15T11:02:09.309Z",
              "processedTime": "2018-03-15T11:02:11.922Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "944a6620-283d-11e8-9671-133d404fd607",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-15T10:42:11.000Z",
              "receivedTime": "2018-03-15T10:42:36.821Z",
              "processedTime": "2018-03-15T10:42:38.076Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "ec5a8df0-2837-11e8-881b-7f141d073ca4",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8048,
              "longitude": -77.0923,
              "asOfTime": "2018-03-15T10:02:17.000Z",
              "receivedTime": "2018-03-15T10:02:06.817Z",
              "processedTime": "2018-03-15T10:02:08.838Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "c407d190-2833-11e8-9671-133d404fd607",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8045,
              "longitude": -77.0923,
              "asOfTime": "2018-03-15T09:32:16.000Z",
              "receivedTime": "2018-03-15T09:32:21.261Z",
              "processedTime": "2018-03-15T09:32:23.203Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "62a55fb0-282b-11e8-9a6e-7f663272511f",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8044,
              "longitude": -77.0922,
              "asOfTime": "2018-03-15T08:32:16.000Z",
              "receivedTime": "2018-03-15T08:32:21.134Z",
              "processedTime": "2018-03-15T08:32:23.834Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "01b118f0-2823-11e8-bdac-b56aa25b6315",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8046,
              "longitude": -77.0925,
              "asOfTime": "2018-03-15T07:32:17.000Z",
              "receivedTime": "2018-03-15T07:32:23.518Z",
              "processedTime": "2018-03-15T07:32:25.201Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "d3b05a00-281e-11e8-9a6e-7f663272511f",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8045,
              "longitude": -77.0923,
              "asOfTime": "2018-03-15T07:02:17.000Z",
              "receivedTime": "2018-03-15T07:02:27.245Z",
              "processedTime": "2018-03-15T07:02:30.032Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "8fbe8a50-281a-11e8-bdac-b56aa25b6315",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8047,
              "longitude": -77.0925,
              "asOfTime": "2018-03-15T06:32:07.000Z",
              "receivedTime": "2018-03-15T06:31:56.343Z",
              "processedTime": "2018-03-15T06:31:58.060Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "8fbe6340-281a-11e8-b3e4-e934528e0ef2",
              "eventType": "StationaryStart",
              "source": "derived",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8047,
              "longitude": -77.0925,
              "asOfTime": "2018-03-15T06:32:07.000Z",
              "receivedTime": "2018-03-15T06:31:56.343Z",
              "processedTime": "2018-03-15T06:31:58.060Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "336353b0-2812-11e8-9671-133d404fd607",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8044,
              "longitude": -77.0923,
              "asOfTime": "2018-03-15T05:32:16.000Z",
              "receivedTime": "2018-03-15T05:32:05.590Z",
              "processedTime": "2018-03-15T05:32:07.140Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "d4651090-2809-11e8-9671-133d404fd607",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.805,
              "longitude": -77.0925,
              "asOfTime": "2018-03-15T04:32:17.000Z",
              "receivedTime": "2018-03-15T04:32:09.031Z",
              "processedTime": "2018-03-15T04:32:11.792Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "a15d6480-2805-11e8-9671-133d404fd607",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8051,
              "longitude": -77.0922,
              "asOfTime": "2018-03-15T04:02:15.000Z",
              "receivedTime": "2018-03-15T04:02:06.991Z",
              "processedTime": "2018-03-15T04:02:08.190Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "687ed120-2801-11e8-aaec-a5724b664d16",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8046,
              "longitude": -77.0922,
              "asOfTime": "2018-03-15T03:32:04.000Z",
              "receivedTime": "2018-03-15T03:31:52.812Z",
              "processedTime": "2018-03-15T03:31:54.791Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "37ddebe0-27fd-11e8-9671-133d404fd607",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8047,
              "longitude": -77.0924,
              "asOfTime": "2018-03-15T03:02:04.000Z",
              "receivedTime": "2018-03-15T03:01:53.656Z",
              "processedTime": "2018-03-15T03:01:55.220Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "d44ade60-27f4-11e8-aaec-a5724b664d16",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8037,
              "longitude": -77.0922,
              "asOfTime": "2018-03-15T02:02:02.000Z",
              "receivedTime": "2018-03-15T02:01:50.896Z",
              "processedTime": "2018-03-15T02:01:52.190Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "77a928e0-27ec-11e8-bdac-b56aa25b6315",
              "eventType": "StationaryEnd",
              "source": "derived",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8062,
              "longitude": -77.0921,
              "asOfTime": "2018-03-15T01:02:09.000Z",
              "receivedTime": "2018-03-15T01:01:58.203Z",
              "processedTime": "2018-03-15T01:02:00.804Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "77a928e0-27ec-11e8-881b-7f141d073ca4",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8062,
              "longitude": -77.0921,
              "asOfTime": "2018-03-15T01:02:09.000Z",
              "receivedTime": "2018-03-15T01:01:58.203Z",
              "processedTime": "2018-03-15T01:02:00.804Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "20db2660-27e4-11e8-bdac-b56aa25b6315",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8047,
              "longitude": -77.0924,
              "asOfTime": "2018-03-15T00:02:27.000Z",
              "receivedTime": "2018-03-15T00:02:17.564Z",
              "processedTime": "2018-03-15T00:02:19.196Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "7a2d5930-27e0-11e8-9a6e-7f663272511f",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T23:35:44.000Z",
              "receivedTime": "2018-03-14T23:36:09.902Z",
              "processedTime": "2018-03-14T23:36:11.059Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "f8b96510-27df-11e8-881b-7f141d073ca4",
              "eventType": "StationaryStart",
              "source": "derived",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8052,
              "longitude": -77.0925,
              "asOfTime": "2018-03-14T23:32:24.000Z",
              "receivedTime": "2018-03-14T23:32:31.357Z",
              "processedTime": "2018-03-14T23:32:33.877Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "f8b8efe0-27df-11e8-9671-133d404fd607",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8052,
              "longitude": -77.0925,
              "asOfTime": "2018-03-14T23:32:24.000Z",
              "receivedTime": "2018-03-14T23:32:31.357Z",
              "processedTime": "2018-03-14T23:32:33.877Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "c16c6e30-27db-11e8-b3e4-e934528e0ef2",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8044,
              "longitude": -77.0921,
              "asOfTime": "2018-03-14T23:02:17.000Z",
              "receivedTime": "2018-03-14T23:02:21.881Z",
              "processedTime": "2018-03-14T23:02:23.114Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "83d49880-27d7-11e8-881b-7f141d073ca4",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8051,
              "longitude": -77.0922,
              "asOfTime": "2018-03-14T22:32:08.000Z",
              "receivedTime": "2018-03-14T22:31:59.167Z",
              "processedTime": "2018-03-14T22:32:01.789Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "28df8190-27cf-11e8-9671-133d404fd607",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8053,
              "longitude": -77.0928,
              "asOfTime": "2018-03-14T21:32:20.000Z",
              "receivedTime": "2018-03-14T21:32:11.963Z",
              "processedTime": "2018-03-14T21:32:13.216Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "db018910-27cd-11e8-9671-133d404fd607",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T21:22:27.000Z",
              "receivedTime": "2018-03-14T21:22:51.754Z",
              "processedTime": "2018-03-14T21:22:53.079Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "d213ebe0-27cd-11e8-bdac-b56aa25b6315",
              "eventType": "SensorTiltHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T21:22:11.000Z",
              "receivedTime": "2018-03-14T21:22:36.026Z",
              "processedTime": "2018-03-14T21:22:38.100Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "c9b8f1c0-27cd-11e8-b3e4-e934528e0ef2",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T21:21:57.000Z",
              "receivedTime": "2018-03-14T21:22:22.944Z",
              "processedTime": "2018-03-14T21:22:24.083Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "c0c33e40-27cd-11e8-9671-133d404fd607",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T21:21:40.000Z",
              "receivedTime": "2018-03-14T21:22:07.099Z",
              "processedTime": "2018-03-14T21:22:09.056Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "439aaf70-27cd-11e8-bdac-b56aa25b6315",
              "eventType": "SensorTiltHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T21:18:11.000Z",
              "receivedTime": "2018-03-14T21:18:37.989Z",
              "processedTime": "2018-03-14T21:18:39.067Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "fe60bd70-27ca-11e8-b3e4-e934528e0ef2",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8045,
              "longitude": -77.0924,
              "asOfTime": "2018-03-14T21:02:17.000Z",
              "receivedTime": "2018-03-14T21:02:21.800Z",
              "processedTime": "2018-03-14T21:02:23.936Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "b9e94300-27c6-11e8-bdac-b56aa25b6315",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8048,
              "longitude": -77.0924,
              "asOfTime": "2018-03-14T20:31:58.000Z",
              "receivedTime": "2018-03-14T20:31:49.758Z",
              "processedTime": "2018-03-14T20:31:51.080Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "ac31fab0-27c4-11e8-b3e4-e934528e0ef2",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T20:16:39.000Z",
              "receivedTime": "2018-03-14T20:17:07.195Z",
              "processedTime": "2018-03-14T20:17:09.072Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "6fb12fc0-27bf-11e8-bdac-b56aa25b6315",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T19:39:11.000Z",
              "receivedTime": "2018-03-14T19:39:38.896Z",
              "processedTime": "2018-03-14T19:39:40.082Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "5ca0a9b0-27bf-11e8-b3e4-e934528e0ef2",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T19:38:43.000Z",
              "receivedTime": "2018-03-14T19:39:06.314Z",
              "processedTime": "2018-03-14T19:39:08.097Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "59a03af0-27bf-11e8-881b-7f141d073ca4",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T19:38:39.000Z",
              "receivedTime": "2018-03-14T19:39:01.678Z",
              "processedTime": "2018-03-14T19:39:03.065Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "544401e0-27bf-11e8-b3e4-e934528e0ef2",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T19:38:28.000Z",
              "receivedTime": "2018-03-14T19:38:52.249Z",
              "processedTime": "2018-03-14T19:38:54.071Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "4abd0ae0-27bf-11e8-9a6e-7f663272511f",
              "eventType": "SensorTiltHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T19:38:10.000Z",
              "receivedTime": "2018-03-14T19:38:36.864Z",
              "processedTime": "2018-03-14T19:38:38.078Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "641298d0-27be-11e8-9a6e-7f663272511f",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.806,
              "longitude": -77.0926,
              "asOfTime": "2018-03-14T19:32:18.000Z",
              "receivedTime": "2018-03-14T19:32:09.501Z",
              "processedTime": "2018-03-14T19:32:11.082Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "6411ae70-27be-11e8-aaec-a5724b664d16",
              "eventType": "StationaryEnd",
              "source": "derived",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.806,
              "longitude": -77.0926,
              "asOfTime": "2018-03-14T19:32:18.000Z",
              "receivedTime": "2018-03-14T19:32:09.501Z",
              "processedTime": "2018-03-14T19:32:11.082Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "moving",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "9ddf4470-27bc-11e8-aaec-a5724b664d16",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T19:19:02.000Z",
              "receivedTime": "2018-03-14T19:19:27.404Z",
              "processedTime": "2018-03-14T19:19:29.075Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "9324d680-27bc-11e8-9a6e-7f663272511f",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T19:18:40.000Z",
              "receivedTime": "2018-03-14T19:19:09.179Z",
              "processedTime": "2018-03-14T19:19:11.066Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "4a6e07e0-27bc-11e8-b3e4-e934528e0ef2",
              "eventType": "SensorTiltHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T19:16:42.000Z",
              "receivedTime": "2018-03-14T19:17:07.070Z",
              "processedTime": "2018-03-14T19:17:09.075Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "3929b650-27bc-11e8-bdac-b56aa25b6315",
              "eventType": "SensorAmbientLightHigh",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": null,
              "longitude": null,
              "asOfTime": "2018-03-14T19:16:12.000Z",
              "receivedTime": "2018-03-14T19:16:38.274Z",
              "processedTime": "2018-03-14T19:16:40.107Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": null,
              "streamLabel": null,
              "primaryStreamId": null,
              "isPrimary": false,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "0bc23c10-27b6-11e8-881b-7f141d073ca4",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8045,
              "longitude": -77.0925,
              "asOfTime": "2018-03-14T18:32:17.000Z",
              "receivedTime": "2018-03-14T18:32:24.168Z",
              "processedTime": "2018-03-14T18:32:26.954Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "a7188e70-27ad-11e8-9671-133d404fd607",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8046,
              "longitude": -77.0923,
              "asOfTime": "2018-03-14T17:32:16.000Z",
              "receivedTime": "2018-03-14T17:32:20.720Z",
              "processedTime": "2018-03-14T17:32:22.098Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "6a1111e0-27a9-11e8-9a6e-7f663272511f",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8046,
              "longitude": -77.0923,
              "asOfTime": "2018-03-14T17:02:09.000Z",
              "receivedTime": "2018-03-14T17:01:59.266Z",
              "processedTime": "2018-03-14T17:02:01.714Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "10fa57e0-27a1-11e8-bdac-b56aa25b6315",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8047,
              "longitude": -77.0923,
              "asOfTime": "2018-03-14T16:02:24.000Z",
              "receivedTime": "2018-03-14T16:02:14.536Z",
              "processedTime": "2018-03-14T16:02:16.270Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "db150750-279c-11e8-881b-7f141d073ca4",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8045,
              "longitude": -77.0921,
              "asOfTime": "2018-03-14T15:32:14.000Z",
              "receivedTime": "2018-03-14T15:32:05.826Z",
              "processedTime": "2018-03-14T15:32:07.872Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "a3c3cab0-2798-11e8-9671-133d404fd607",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8049,
              "longitude": -77.0924,
              "asOfTime": "2018-03-14T15:02:07.000Z",
              "receivedTime": "2018-03-14T15:01:55.494Z",
              "processedTime": "2018-03-14T15:01:57.078Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          },
          {
              "shipmentId": "UNITED-flexcabletest-1",
              "organization": "TESTMART",
              "eventId": "52d6e8b0-2790-11e8-9a6e-7f663272511f",
              "eventType": "GeolocationUpdate",
              "source": "device",
              "sourceId": null,
              "statusType": null,
              "currentLeg": 1,
              "fromPoi": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "toPoi": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "latitude": 38.8044,
              "longitude": -77.0923,
              "asOfTime": "2018-03-14T14:02:16.000Z",
              "receivedTime": "2018-03-14T14:02:23.476Z",
              "processedTime": "2018-03-14T14:02:25.323Z",
              "etaStatus": "",
              "carrier": "DART",
              "lifeCycle": "inTransit",
              "location": "enRoute",
              "origin": "NEMC NORTH EAST MIX CNTR-PGDIS [B278]",
              "destination": "SEMC SOUTH EST MIX CNTR-PGDLLC [B340]",
              "movementState": "stationary",
              "mode": "ocean",
              "streamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "streamLabel": "Device: 99000512005931",
              "primaryStreamId": "UNITED-flexcabletest-1|TESTMART|shipment|99000512005931|sendum-sensor-feed-json|device",
              "isPrimary": true,
              "version": "1.1.0",
              "userId": null,
              "pairedStreamId": "99000512005931"
          }],
  }
  this.test = this.parentValue.shipmentEvents;
  }

}
